# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

Creating the dataset

y = b0 +b1*x1 +b2*x2 +b3*x3 +b4*x4


In [15]:
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_studied Hours_slept iQ '.split())
df.head(2)

Hours_studied  Hours_slept        iQ
0       2.150246     1.085211  4.299632
1       4.350124     6.695615  3.935018

In [20]:
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["New Delhi" , "Pune" , "Bangalore"]))
 

df['Location'] = location

df.head()

Hours_studied  Hours_slept        iQ   Location      Marks
0       2.150246     1.085211  4.299632  Bangalore  33.138227
1       4.350124     6.695615  3.935018       Pune  46.012076
2       2.202233     9.376619  6.177840  New Delhi  62.791760
3       8.924395     3.762944  8.378182  New Delhi  63.674497
4       7.171806     8.664971  9.767834  New Delhi  67.302704

In [21]:
df['Marks'] = (1.73 + (3.34*df['Hours_studied'])
                    + (2.45*df['Hours_slept'])
                    + (1.83*df['iQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)


In [5]:
df.head()

Hours_studied  Hours_slept        iQ   Location      Marks
0       1.531130     6.241712  3.931965  New Delhi  42.562722
1       2.250000     4.137144  7.865846  New Delhi  39.819597
2       8.975945     6.687917  6.340032       Pune  76.628923
3       2.737767     0.587730  5.588760       Pune  24.200189
4       1.545774     9.663307  6.022966  New Delhi  43.502877

## Importing the dataset

In [6]:
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[1.5311302067316257 6.241711913811301 3.931964812111933 'New Delhi']
 [2.249999933675244 4.137143728992287 7.865845939052463 'New Delhi']
 [8.975945214020399 6.6879170263383685 6.34003150748363 'Pune']
 [2.737767117527232 0.5877301705487548 5.5887603184917065 'Pune']
 [1.5457735074678602 9.663306573360424 6.0229659706315175 'New Delhi']
 [9.858185667857837 7.4621136602056835 8.593341800567378 'Bangalore']
 [1.4064417142166021 5.768703253893004 8.640356830607901 'Bangalore']
 [6.026151738825075 9.839185321329328 9.322696008154935 'Pune']
 [4.129832017588519 5.719987475780168 0.5542090498878971 'Pune']
 [4.613819288805357 5.5954229854761515 7.4347758749962045 'New Delhi']
 [2.4477581247792832 6.273161197873742 4.4261924331628215 'Pune']
 [3.772584903659317 2.1282593810187334 8.25724977262119 'Pune']
 [3.1398337275981096 2.143893424268314 5.609470303933233 'Pune']
 [8.371757533615838 0.35365966793199705 6.956055649814714 'Pune']
 [4.314263053719592 4.007815368230789 0.648716669311532 'Ba

In [7]:
print(y)

[42.56272156 39.81959744 76.62892334 24.20018891 43.50287653 77.49682235
 47.41245951 75.12543446 31.38393297 48.9962183  41.35727885 48.38487428
 31.38567722 57.56253826 30.62473985 49.10053338 39.75441488 47.47045228
 68.32959366 55.19647411 60.04487393 64.91666484 81.16512187 42.74377348
 61.09738103 68.69867938 61.76989475 63.61656585 75.1575283  45.93764135
 32.61866249 74.67407047 21.68487123 48.87107275 68.43220122 48.80290464
 27.67796223 75.56719018 48.65433321 72.2213334  58.2333018  22.44224038
 47.09481056 38.65209356 54.93118272 51.95079458 54.50216967 41.08547359
 61.27893515 51.58690049]


## Encoding categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])


In [9]:
print(X)






[[0.0 1.0 0.0 1.5311302067316257 6.241711913811301 3.931964812111933]
 [0.0 1.0 0.0 2.249999933675244 4.137143728992287 7.865845939052463]
 [0.0 0.0 1.0 8.975945214020399 6.6879170263383685 6.34003150748363]
 [0.0 0.0 1.0 2.737767117527232 0.5877301705487548 5.5887603184917065]
 [0.0 1.0 0.0 1.5457735074678602 9.663306573360424 6.0229659706315175]
 [1.0 0.0 0.0 9.858185667857837 7.4621136602056835 8.593341800567378]
 [1.0 0.0 0.0 1.4064417142166021 5.768703253893004 8.640356830607901]
 [0.0 0.0 1.0 6.026151738825075 9.839185321329328 9.322696008154935]
 [0.0 0.0 1.0 4.129832017588519 5.719987475780168 0.5542090498878971]
 [0.0 1.0 0.0 4.613819288805357 5.5954229854761515 7.4347758749962045]
 [0.0 0.0 1.0 2.4477581247792832 6.273161197873742 4.4261924331628215]
 [0.0 0.0 1.0 3.772584903659317 2.1282593810187334 8.25724977262119]
 [0.0 0.0 1.0 3.1398337275981096 2.143893424268314 5.609470303933233]
 [0.0 0.0 1.0 8.371757533615838 0.35365966793199705 6.956055649814714]
 [1.0 0.0 0.0 4.314

## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_test

array([75.1575283 , 48.38487428, 41.35727885, 22.44224038, 76.62892334,
       63.61656585, 48.65433321, 74.67407047, 81.16512187, 43.50287653])

## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




Predicted  Actual
[[66.79 75.16]
 [45.28 48.38]
 [43.32 41.36]
 [31.42 22.44]
 [70.86 76.63]
 [69.12 63.62]
 [55.37 48.65]
 [85.16 74.67]
 [80.96 81.17]
 [50.38 43.5 ]]


In [ ]:

np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)) ,1))

In [ ]:
len(y_pred)

In [ ]:
y_test

In [ ]:
y_pred

In [ ]:
help(np.random.rand)*10